<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>AuraUI.Demo</RootNamespace>
    <AssemblyName>AuraUI.Demo</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AuraUI.Controls\AuraUI.Controls.csproj" />
    <ProjectReference Include="..\..\src\AuraUI.Themes.Fluent\AuraUI.Themes.Fluent.csproj" />
    <ProjectReference Include="..\..\src\AuraUI.Themes.Material\AuraUI.Themes.Material.csproj" />
  </ItemGroup>
</Project>
